"""migration

Revision ID: 67ef26e14ebc
Revises: 
Create Date: 2023-09-09 13:12:11.492855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67ef26e14ebc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spotify_url', sa.Text(), nullable=False),
    sa.Column('soundcloud_url', sa.Text(), nullable=False),
    sa.Column('instagram_url', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('invite',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invited_by', sa.String(length=32), nullable=False),
    sa.Column('revoked_by', sa.String(length=32), nullable=True),
    sa.Column('token', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['user.username'], ),
    sa.ForeignKeyConstraint(['revoked_by'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('token')
    )
    op.create_table('subdivision',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('social', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['social'], ['social.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('social', sa.Integer(), nullable=False),
    sa.Column('subdivision', sa.Integer(), nullable=False),
    sa.Column('picture', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('aliases', sa.Text(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['social'], ['social.id'], ),
    sa.ForeignKeyConstraint(['subdivision'], ['subdivision.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('release',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subdivision_id', sa.Integer(), nullable=False),
    sa.Column('added_by_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('producers', sa.Text(), nullable=False),
    sa.Column('artists', sa.Text(), nullable=False),
    sa.Column('cover', sa.Text(), nullable=False),
    sa.Column('spotify_url', sa.Text(), nullable=True),
    sa.Column('soundcloud_url', sa.Text(), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=False),
    sa.Column('release_type', sa.String(length=6), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("release_type IN ('album', 'single')"),
    sa.ForeignKeyConstraint(['added_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['subdivision_id'], ['subdivision.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('release')
    op.drop_table('producer')
    op.drop_table('subdivision')
    op.drop_table('invite')
    op.drop_table('user')
    op.drop_table('social')
    # ### end Alembic commands ###
